---
- name: create target install dir...
  become: yes
  become_user: root
  file:
    path: '{{galaxify_target_dir}}'
    state: directory
    mode: 0755

- name: templatize...
  become: yes
  become_user: root
  with_items:
    - f: LICENSE
    - f: README.md
    - f: galaxify
      m: '0755'
    - f: meta-main.yml
    - f: test.yml
    - f: circle.yml
    - f: .travis.yml
  template:
    src: '{{item.f}}.j2'
    dest: '{{galaxify_target_dir}}/{{item.f}}'
    mode: '{{item.m | default("0644")}}'

- name: copy...
  become: yes
  become_user: root
  with_items:
    - f: task-main.yml
    - f: .gitignore
    - f: .pre-commit-config.yaml
  copy:
    src: '{{item.f}}'
    dest: '{{galaxify_target_dir}}/{{item.f}}'
    mode: '{{item.m | default("0644")}}'

- name: link the released galaxify...
  become: yes
  become_user: root
  with_items:
    - galaxify
  file:
    src: '{{galaxify_target_dir}}/{{item}}'
    dest: '{{galaxify_install_dir}}/{{item}}'
    state: link
