---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: create target install dir {{ galaxify_target_dir }}...
  become: '{{ galaxify_privilege_escalate }}'
  become_user: root
  file:
    path: '{{ galaxify_target_dir }}'
    state: directory
    mode: 0755

- name: templatize...
  become: '{{ galaxify_privilege_escalate }}'
  become_user: root
  with_items:
    - f: LICENSE
    - f: README.md
    - f: galaxify
      m: '0755'
    - f: meta-main.yml
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ galaxify_target_dir }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'

- name: copying to {{ galaxify_target_dir }}...
  become: '{{ galaxify_privilege_escalate }}'
  become_user: root
  with_items:
    - f: tasks-main.yml
    - f: .gitignore
    - f: platform-matrix-v1.json
    - f: build.yml
    - f: test.yml
  copy:
    src: '{{ item.f }}'
    dest: '{{ galaxify_target_dir }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'

- name: linking {{ galaxify_link }} to {{ galaxify_target_exe }}
  become: '{{ galaxify_privilege_escalate }}'
  become_user: root
  file:
    src: '{{ galaxify_target_exe }}'
    dest: '{{ galaxify_link }}'
    state: link
