---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: create target install dir...
  become: '{{ galaxify_privilege_escalate }}'
  become_user: root
  file:
    path: '{{ galaxify_target_dir }}'
    state: directory
    mode: 0755

- name: templatize...
  become: '{{ galaxify_privilege_escalate }}'
  become_user: root
  with_items:
    - f: LICENSE
    - f: README.md
    - f: galaxify
      m: '0755'
    - f: meta-main.yml
    - f: test.yml
    - f: .travis.yml
    - f: requirements.txt
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ galaxify_target_dir }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'

- name: copy...
  become: '{{ galaxify_privilege_escalate }}'
  become_user: root
  with_items:
    - f: tasks-main.yml
    - f: .gitignore
    - f: .pre-commit-config.yaml
    - f: dcb-os.yml
  copy:
    src: '{{ item.f }}'
    dest: '{{ item.d | default(galaxify_target_dir) }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'

- name: link the released galaxify...
  become: '{{ galaxify_privilege_escalate }}'
  become_user: root
  with_items:
    - galaxify
  file:
    src: '{{ galaxify_target_dir }}/{{ item }}'
    dest: '{{ galaxify_install_dir }}/{{ item }}'
    state: link
